# docker compose up --build

services:
# +--------------------+
# |       MONGO        |
# +--------------------+

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: app_pw
      MONGO_INITDB_DATABASE: suspicious
    networks:
      - app-network

# +--------------------+
# |       MYSQL        |
# +--------------------+
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: suspicious
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root_pwd
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

# +--------------------+
# |       KAFKA        |
# +--------------------+
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    restart: unless-stopped
    ports:
      - "9092:9092" # host access (your local FastAPI -> localhost:9092)
    environment:
      CLUSTER_ID: "Mf_-9PUJQnCI6eQZzgFTlg"

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      # --- Listeners ---
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # --- Single-node dev defaults ---
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - app-network

# +--------------------+
# |    PRODUCER        |
# +--------------------+
  producer:
    build:
      context: ./producer        # Build from local Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
      MONGO_DB: "suspicious"
      MONGO_COLLECTION: "records"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      KAFKA_TOPIC: "raw-records"
    networks:
      - app-network

# +--------------------+
# |     CONSUMER       |
# +--------------------+
  consumer:
    build:
      context: ./consumer            # Build from local Dockerfile
      dockerfile: Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      KAFKA_TOPIC: "raw-records"
      KAFKA_GROUP_ID: "mysql-loader"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      MYSQL_DATABASE: suspicious
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root_pwd
    networks:
      - app-network

# +--------------------+
# |    ANALYTICS API   |
# +--------------------+
  analytics-api:
    build:
      context: ./analytics-api       # Build from local Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      DB_HOST: "mysql"
      DB_PORT: "3306"
      MYSQL_DATABASE: suspicious
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root_pwd
    networks:
      - app-network


volumes:
  mongo_data:
  mysql_data:


networks:
  app-network:
    driver: bridge        
    driver_opts:
      com.docker.network.bridge.name: app_br
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1